### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by danilind** [tc216997/heatmap#1]
Hi.
Really love this overview of the marked, but the last couple of days it seems that the data have not been updated.

**Comment by tc216997** [comment]
Hi, are you using firefox? You might have to clear your cache. It was giving me that problem before on firefox. On google chrome, it's updating correctly for me.

**Comment by danilind** [comment]
I'm using chrome. I tried a hard reload (crtl+f5), and it worked. Thanks
